name: My fancy CI pipeline ✨

on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run lint check
        run: npm run lint
